[variables]
bgbackground1=#@#Images\background.jpg

GameScreenTitle=Have fun
 
Toolbar1Loc=%ProgramData%\Microsoft\Windows\Start Menu\Programs\Games
Toolbar2Loc=
Toolbar3Loc=
Toolbar4Loc=
Toolbar5Loc=
Toolbar6Loc=
Toolbar7Loc=
Toolbar8Loc=

Toolbar1Count=1
Toolbar2Count=7
Toolbar3Count=13
Toolbar4Count=12
Toolbar5Count=6
Toolbar6Count=0
Toolbar7Count=0
Toolbar8Count=0

Update=1

tempwall=#@#Images\background.jpg
tempwall2=#bgbackground1#
