[measureTopUsage1CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=1
Substitute="":"."
Group=NonOverview

[measureTopUsage2CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=2
Substitute="":"."
Group=NonOverview

[measureTopUsage3CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=3
Substitute="":"."
Group=NonOverview

[measureTopUsage4CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=4
Substitute="":"."
Group=NonOverview

[measureTopUsage5CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=5
Substitute="":"."
Group=NonOverview

[measureTopUsage6CPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=CPU
Percent=1
Index=6
Substitute="":"."
Group=NonOverview