[Serial3_1]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=4R
Text="3.1. "
Group=Hidethis

[meterRAMTotalCapacityTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="RAM Total Capacity: "
Group=Hidethis

[meterRAMTotalCapacityValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=121
MeasureName=measurePhysMemTotalReadable
Text="%1 GB"
NumOfDecimals=2
Group=Hidethis
ClipString=2

[Serial3_2]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="3.2. "
Group=Hidethis

[meterRAMManufacturerTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="RAM Manufacturer: "
Group=Hidethis

[meterRAMManufacturerValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=126
MeasureName=measureRAMManufacturer
Text="%1"
Group=Hidethis
ClipString=2

[Serial3_3]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="3.3. "
Group=Hidethis

[meterRAMTypeTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="RAM Type: "
Group=Hidethis

[meterRAMTypeValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=164
MeasureName=measureRAMType
Text="%1"
Group=Hidethis
ClipString=2

[Serial3_4]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="3.4. "
Group=Hidethis

[meterRAMDeviceLocatorsTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="RAM Locators: "
Group=Hidethis

[meterRAMDeviceLocatorsValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=147
MeasureName=measureRAMDeviceLocators
Text="%1"
Group=Hidethis
ClipString=2

[Serial3_5]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="3.5. "
Group=Hidethis

[meterRAMCapacitiesTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="RAM Capacities: "
Group=Hidethis

[meterRAMCapacitiesValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=140
MeasureName=measureRAMCapacities
Text="%1"
Group=Hidethis
ClipString=2

[Serial3_6]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="3.6. "
Group=Hidethis

[meterRAMPartNumbersTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="RAM Part No.: "
Group=Hidethis

[meterRAMPartNumbersValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=149
MeasureName=measureRAMPartNumbers
Text="%1"
Group=Hidethis
ClipString=2

[Serial3_7]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="3.7. "
Group=Hidethis

[meterRAMSpeedsTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="RAM Speeds: "
Group=Hidethis

[meterRAMSpeedsValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=153
MeasureName=measureRAMSpeeds
Text="%1"
Group=Hidethis
ClipString=2