[Serial4_1]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=4R
Text="4.1. "
Group=Hidethis

[meterMotherboardNameTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="Motherboard Name: "
Group=Hidethis

[meterMotherboardNameValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=122
MeasureName=measureMotherboardname
Text="%1"
Group=Hidethis
ClipString=2

[Serial4_2]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="4.2. "
Group=Hidethis

[meterGPUNameTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="GPU Name: "
Group=Hidethis

[meterGPUNameValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=162
MeasureName=measureGPUName
Text="%1"
Group=Hidethis
ClipString=2