[Serial6_1]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=4R
Text="6.1. "
Group=Hidethis

[meterIPAddressesTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="IP Addresses:"
Group=Hidethis

[meterIPAddressesValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=151
MeasureName=measureIPValues
Text="%1"
Group=Hidethis
ClipString=2

[Serial6_2]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="6.2. "
Group=Hidethis

[meterNetmasksTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="NetMasks: "
Group=Hidethis

[meterNetmasksValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=166
MeasureName=measureSubnetMaskValues
Text="%1"
Group=Hidethis
ClipString=2

[Serial6_3]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="6.3. "
Group=Hidethis

[meterGatewaysTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="Gateways: "
Group=Hidethis

[meterGatewaysValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=166
MeasureName=measureDefaultGatewayValues
Text="%1"
Group=Hidethis
ClipString=2

[Serial6_4]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="6.4. "
Group=Hidethis

[meterDNSServersTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="DNS Servers: "
Group=Hidethis

[meterDNSServerValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=152
MeasureName=measureDNSServerValues
Text="%1"
Group=Hidethis
ClipString=2

[Serial6_5]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="6.5. "
Group=Hidethis

[meterMACAddressesTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="MAC Addresses: "
Group=Hidethis

[meterMACAddressesValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=140
MeasureName=measureMACAddressValues
Text="%1"
ClipString=2
Group=Hidethis

[Serial6_6]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="6.6. "
Group=Hidethis

[meterNetworkCardNamesTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="NIC Names:"
Group=Hidethis

[meterNetworkCardNamesValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=162
MeasureName=measureNetworkCardNameValues
Text="%1"
ClipString=2
Group=Hidethis

[Serial6_7]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="6.7. "
Group=Hidethis

[meterNetworkCardTypesTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="NIC Types:"
Group=Hidethis

[meterNetworkCardTypesValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=163
MeasureName=measureNetworkCardTypeValues
Text="%1"
Group=Hidethis
ClipString=2

[Serial6_8]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#-8)
Y=0R
Text="6.8. "
Group=Hidethis

[meterNetworkCardSpeedsTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="NIC Speeds:"
Group=Hidethis

[meterNetworkCardSpeedsValues]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=157
MeasureName=measureNetworkCardSpeedValues
Text="%1"
ClipString=2
Group=Hidethis
