[meterServerStatusTitle]
Meter=String
MeterStyle=StyleBoldLeft
X=(#widthtoggle#+310)
Y=0R
W=182
H=18
Text="Server Status"
Group=Hidethis

[meterServer1Image]
Meter=Image
X=(#widthtoggle#+247)
Y=0R
W=10
H=10
Group=Hidethis

[meterServer1]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer1
Text="BSNLRouter: %1"
Group=Hidethis

[meterServer2Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer2]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer2
Text="TataSkyRouter: %1"
Group=Hidethis

[meterServer3Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer3]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer3
Text="AirtelRouter: %1"
Group=Hidethis

[meterServer4Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer4]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer4
Text="PfSense: %1"
Group=Hidethis

[meterServer5Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer5]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer5
Text="WifiOld: %1"
Group=Hidethis

[meterServer6Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer6]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer6
Text="WifiNew: %1"
Group=Hidethis

[meterServer7Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer7]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer7
Text="CiscoWifiAPDDWRT: %1"
Group=Hidethis

[meterServer8Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer8]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer8
Text="proxmoxA: %1"
Group=Hidethis

[meterServer9Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer9]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer9
Text="proxmoxJ: %1"
Group=Hidethis

[meterServer10Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer10]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer10
Text="Legend: %1"
Group=Hidethis

[meterServer11Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer11]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer11
Text="Tulip: %1"
Group=Hidethis

[meterServer12Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer12]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer12
Text="xammpserver: %1"
Group=Hidethis

[meterServer13Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer13]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer13
Text="Flourish: %1"
Group=Hidethis

[meterServer14Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer14]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer14
Text="PowerOutageRouter: %1"
Group=Hidethis

