[meterServerStatusTitle]
Meter=String
MeterStyle=StyleBoldLeft
X=(#widthtoggle#+310)
Y=0R
W=182
H=18
Text="Server Status"
Group=Hidethis

[meterServer1Image]
Meter=Image
X=(#widthtoggle#+247)
Y=0R
W=10
H=10
Group=Hidethis

[meterServer1]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer1
Text="01.PfSense: %1"
Group=Hidethis

[meterServer2Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer2]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer2
Text="02.TataSkyRouter: %1"
Group=Hidethis

[meterServer3Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer3]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer3
Text="03.AirtelRouter: %1"
Group=Hidethis

[meterServer4Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer4]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer4
Text="04.BSNLRouter: %1"
Group=Hidethis

[meterServer5Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer5]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer5
Text="05.WifiOld: %1"
Group=Hidethis

[meterServer6Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer6]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer6
Text="06.WifiNew: %1"
Group=Hidethis

[meterServer7Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer7]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer7
Text="07.CiscoWifiDDWRT: %1"
Group=Hidethis

[meterServer8Image]
Meter=Image
X=(#widthtoggle#+247)
Y=4R
W=10
H=10
Group=Hidethis

[meterServer8]
Meter=String
MeterStyle=StyleBoldLeft
X=10R
Y=-2r
MeasureName=measureServer8
Text="08.Flourish: %1"
Group=Hidethis

