[meterWIFIDetailsTitle]
Meter=String
MeterStyle=StyleBoldLeft
X=(#widthtoggle#+310)
Y=0R
W=182
H=18
Text="WIFI Details"
Group=Hidethis

[Serial11_1]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#+247)
Y=0R
Text="11.1. "
Group=Hidethis

[meterWIFISSIDTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="SSID:"
Group=Hidethis

[meterWIFISSIDValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=151
MeasureName=measureWIFISSID
Text="%1"
Group=Hidethis
ClipString=2

[Serial11_2]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#+247)
Y=0R
Text="11.2. "
Group=Hidethis

[meterWIFIQualityTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="Quality: "
Group=Hidethis

[meterWIFIQualityValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=166
MeasureName=measureWIFIQuality
Text="%1"
Group=Hidethis
ClipString=2


[Serial11_3]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#+247)
Y=0R
Text="11.3. "
Group=Hidethis

[meterWIFIEncryptionTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="Encryption: "
Group=Hidethis

[meterWIFIEncryptionValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=166
MeasureName=measureWIFIEncryption
Text="%1"
Group=Hidethis
ClipString=2

[Serial11_4]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#+247)
Y=0R
Text="11.4. "
Group=Hidethis

[meterWIFIAuthTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="Auth Type: "
Group=Hidethis

[meterWIFIAuthValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=166
MeasureName=measureWIFIAuth
Text="%1"
Group=Hidethis
ClipString=2

[Serial11_5]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#+247)
Y=0R
Text="11.5. "
Group=Hidethis

[meterWIFIPhyTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="Bands: "
Group=Hidethis

[meterWIFIPhyValue]
Meter=String
MeterStyle=StyleBoldLeft
X=4R
Y=0r
W=166
MeasureName=measureWIFIPhy
Text="%1"
Group=Hidethis
ClipString=2

[Serial11_6]
Meter=String
MeterStyle=StyleLeft
X=(#widthtoggle#+247)
Y=0R
Text="11.6. "
Group=Hidethis

[meterWIFINetworksTitle]
Meter=String
MeterStyle=StyleLeft
X=3R
Y=0r
Text="Available Networks: [\13][\10]"
Group=Hidethis

[meterWIFINetworksValue]
Meter=String
MeterStyle=StyleBoldLeft
X=((#widthtoggle#+247)+28)
Y=0R
W=186
MeasureName=measureWIFINetworks
Text="%1"
Group=Hidethis
ClipString=2
