[StyleLeft]
FontFace=Tahoma
FontSize=8
FontColor=255,255,255,205
StringAlign=Left
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,20
AntiAlias=1
ClipString=1

[StyleRight]
FontFace=Tahoma
FontSize=8
FontColor=255,255,255,205
StringAlign=Right
StringStyle=Normal
StringEffect=Shadow
FontEffectColor=0,0,0,20
AntiAlias=1
ClipString=1

[StyleBoldLeft]
FontFace=Tahoma
FontSize=8
FontColor=255,255,255,205
StringAlign=Left
;  StringStyle=Bold
FontWeight=950
StringEffect=Shadow
FontEffectColor=0,0,0,20
AntiAlias=1
ClipString=1

[StyleBoldRight]
FontFace=Tahoma
FontSize=8
FontColor=255,255,255,205
StringAlign=Right
;  StringStyle=Bold
FontWeight=950
StringEffect=Shadow
FontEffectColor=0,0,0,20
AntiAlias=1
ClipString=1















































[styleTitle]
FontFace=Trebuchet MS
FontSize=10
FontColor=255,255,255,205
StringAlign=Center

StringStyle=Bold
StringCase=Upper

StringEffect=Shadow
FontEffectColor=0,0,0,50
AntiAlias=1
ClipString=1

[styleLeftText]
FontFace=Trebuchet MS
FontSize=8
FontColor=255,255,255,205
StringAlign=Left

StringStyle=Bold
StringCase=None

StringEffect=Shadow
FontEffectColor=0,0,0,20
AntiAlias=1
ClipString=1

[styleRightText]
FontFace=Trebuchet MS
FontSize=8
FontColor=255,255,255,205
StringAlign=Right

StringStyle=Bold
StringCase=None

StringEffect=Shadow
FontEffectColor=0,0,0,20
AntiAlias=1
ClipString=1

[styleBar]
BarColor=235,170,0,255
BarOrientation=HORIZONTAL
SolidColor=255,255,255,15
