#!/usr/bin/env python

def main():
    print("Size: 0 bytes (0 GB)")
    print("Memory form factor: 0x09 DIMM")
    print("Memory type: 0x02 (Unknown)")
    print("Type detail: 0x80 (Synchronous)")
    print("Unknown speed")
    print("=======================")
    print("Size: 4,294,967,296 bytes (4 GB)")
    print("Memory form factor: 0x09 DIMM")
    print("Memory type: 0x18 (DDR3)")
    print("Type detail: 0x80 (Synchronous)")
    print("Speed: 1,600 MT/s")
    print("=======================")
    print("Size: 0 bytes (0 GB)")
    print("Memory form factor: 0x09 DIMM")
    print("Memory type: 0x02 (Unknown)")
    print("Type detail: 0x80 (Synchronous)")
    print("Unknown speed")
    print("=======================")
    print("Size: 4,294,967,296 bytes (4 GB)")
    print("Memory form factor: 0x09 DIMM")
    print("Memory type: 0x18 (DDR3)")
    print("Type detail: 0x80 (Synchronous)")
    print("Speed: 1,600 MT/s")
    print("=======================")
    print("Size: 4,294,967,296 bytes (4 GB)")
    print("Memory form factor: 0x09 DIMM")
    print("Memory type: 0x18 (DDR3)")
    print("Type detail: 0x80 (Synchronous)")
    print("Speed: 1,600 MT/s")
    print("=======================")
    print("Size: 4,294,967,296 bytes (4 GB)")
    print("Memory form factor: 0x09 DIMM")
    print("Memory type: 0x18 (DDR2)")
    print("Type detail: 0x80 (Synchronous)")
    print("Speed: 1,600 MT/s")
    print("=======================")
    print("Size: 4,294,967,296 bytes (4 GB)")
    print("Memory form factor: 0x09 DIMM")
    print("Memory type: 0x18 (DDR3)")
    print("Type detail: 0x80 (Synchronous)")
    print("Speed: 1,600 MT/s")
    print("=======================")
    return

if __name__ == "__main__":
    main()
